# Generated by Django 6.0.1 on 2026-02-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppDownload',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.TextField(blank=True, null=True)),
                ('appstore', models.TextField(blank=True, null=True)),
                ('playstore', models.TextField(blank=True, null=True)),
                ('title_position', models.SmallIntegerField(blank=True, null=True)),
                ('divide', models.SmallIntegerField(blank=True, null=True)),
                ('font', models.TextField(blank=True, null=True)),
                ('titlecolor', models.TextField(blank=True, db_column='titleColor', null=True)),
                ('fontcolor', models.TextField(blank=True, db_column='fontColor', null=True)),
                ('listcolor', models.TextField(blank=True, db_column='listColor', null=True)),
                ('iconcolor', models.TextField(blank=True, db_column='iconColor', null=True)),
                ('buttonbgcolor', models.TextField(blank=True, db_column='buttonBgColor', null=True)),
                ('buttonfontcolor', models.TextField(blank=True, db_column='buttonFontColor', null=True)),
            ],
            options={
                'db_table': 'app_download',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppDownloadList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'app_download_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppDownloadListTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_download_list_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppDownloadTitle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'app_download_title',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppDownloadTitlePosition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('top', models.SmallIntegerField(blank=True, null=True)),
                ('left', models.SmallIntegerField(blank=True, null=True)),
                ('rotate', models.SmallIntegerField(blank=True, null=True)),
                ('size', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_download_title_position',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppDownloadTitleTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_download_title_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('area', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('open', models.TextField(blank=True, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
                ('longitude', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'branches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BranchPhone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'branch_phone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'collateral',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CollateralTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'collateral_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'conditions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConditionTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'condition_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.TextField(blank=True, null=True)),
                ('index', models.SmallIntegerField(blank=True, null=True)),
                ('font', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('number', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CTA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtaSubtitle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CTA_subtitle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtaTitle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CTA_title',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'document',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'document_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('font', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'font',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('logotext', models.TextField(blank=True, db_column='logoText', null=True)),
                ('facebook', models.TextField(blank=True, null=True)),
                ('instagram', models.TextField(blank=True, null=True)),
                ('twitter', models.TextField(blank=True, null=True)),
                ('bgcolor', models.TextField(blank=True, db_column='bgColor', null=True)),
                ('fontcolor', models.TextField(blank=True, db_column='fontColor', null=True)),
                ('accentcolor', models.TextField(blank=True, db_column='accentColor', null=True)),
                ('iconcolor', models.TextField(blank=True, db_column='iconColor', null=True)),
                ('titlesize', models.SmallIntegerField(blank=True, db_column='titleSize', null=True)),
                ('fontsize', models.SmallIntegerField(blank=True, db_column='fontSize', null=True)),
            ],
            options={
                'db_table': 'footer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FooterTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('copyright', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'footer_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('logo', models.TextField(blank=True, null=True)),
                ('active', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'header',
                'db_table_comment': 'Headeer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HeaderMenu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('font', models.BigIntegerField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('index', models.SmallIntegerField(blank=True, null=True)),
                ('visible', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'header_menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HeaderMenuTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'header_menu_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HeaderStyle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bgcolor', models.TextField(blank=True, db_column='bgColor', null=True)),
                ('fontcolor', models.TextField(blank=True, db_column='fontColor', null=True)),
                ('hovercolor', models.TextField(blank=True, db_column='hoverColor', null=True)),
                ('height', models.SmallIntegerField(blank=True, null=True)),
                ('sticky', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'header_style',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HeaderSubmenu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('font', models.BigIntegerField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('index', models.SmallIntegerField(blank=True, null=True)),
                ('visible', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'header_submenu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HeaderSubmenuTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'header_submenu_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HeaderTertiaryMenu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('font', models.TextField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('index', models.SmallIntegerField(blank=True, null=True)),
                ('visible', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'header_tertiary_menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HeaderTertiaryMenuTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'header_tertiary_menu_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(blank=True, null=True)),
                ('file', models.TextField(blank=True, null=True)),
                ('time', models.SmallIntegerField(blank=True, null=True)),
                ('index', models.SmallIntegerField(blank=True, null=True)),
                ('visible', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hero_slider',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrPolicy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.TextField(blank=True, null=True)),
                ('visual_type', models.TextField(blank=True, null=True)),
                ('visual_preset', models.TextField(blank=True, null=True)),
                ('font_color', models.TextField(blank=True, null=True)),
                ('bg_color', models.TextField(blank=True, null=True)),
                ('fontsize', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hr_policy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrPolicyTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hr_policy_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.SmallIntegerField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.SmallIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('department', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'job_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lang_code', models.TextField(blank=True, null=True)),
                ('lang_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'language',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.TextField(blank=True, null=True)),
                ('video', models.TextField(blank=True, null=True)),
                ('feature', models.BooleanField(blank=True, null=True)),
                ('render', models.BooleanField(blank=True, null=True)),
                ('readtime', models.SmallIntegerField(blank=True, null=True)),
                ('slug', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'news_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsCategoryTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news_category_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsContentTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('font', models.TextField(blank=True, null=True)),
                ('family', models.TextField(blank=True, null=True)),
                ('weight', models.TextField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news_content_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsImages',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news_images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsShortdescTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('font', models.TextField(blank=True, null=True)),
                ('family', models.TextField(blank=True, null=True)),
                ('weight', models.TextField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news_shortdesc_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsSocials',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('social', models.TextField(blank=True, null=True)),
                ('icon', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news_socials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsTitleTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('font', models.TextField(blank=True, null=True)),
                ('family', models.TextField(blank=True, null=True)),
                ('weight', models.TextField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'news_title_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PageDescriptionTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('font', models.TextField(blank=True, null=True)),
                ('family', models.TextField(blank=True, null=True)),
                ('weight', models.TextField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'page_description_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('style', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PageTitleTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('font', models.TextField(blank=True, null=True)),
                ('family', models.TextField(blank=True, null=True)),
                ('weight', models.TextField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'page_title_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCollaterial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'product_collaterial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCondition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'product_condition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_fee_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_fee_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_interest_rate', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('max_interest_rate', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('term_months', models.SmallIntegerField(blank=True, null=True)),
                ('min_processing_hours', models.SmallIntegerField(blank=True, null=True)),
                ('max_processing_hoyrs', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'product_document',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'product_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductTypeTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_type_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Service_card',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceCardTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('short_desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Service_card_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceCollateral',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'service_collateral',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceCondition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'service_condition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'service_document',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicesTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Services_translations',
                'managed': False,
            },
        ),
    ]
