# Generated by Django 6.0.1 on 2026-02-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'about_page',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AboutPageBlock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('index', models.SmallIntegerField(blank=True, null=True)),
                ('visible', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'about_page_block',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AboutPageMedia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.TextField(blank=True, null=True)),
                ('aspect_ratio', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'about_page_media',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AboutPageSection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('index', models.SmallIntegerField(blank=True, null=True)),
                ('visible', models.BooleanField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'about_page_section',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AboutPageSectionTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('fontsize', models.TextField(blank=True, null=True)),
                ('fontweight', models.TextField(blank=True, null=True)),
                ('fontfamily', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'about_page_section_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AboutPageTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('fontcolor', models.TextField(blank=True, null=True)),
                ('fontsize', models.TextField(blank=True, null=True)),
                ('fontweight', models.TextField(blank=True, null=True)),
                ('fontfamily', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'about_page_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('visible', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_value',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreValueDescTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True)),
                ('fontcolor', models.TextField(blank=True, null=True)),
                ('fontsize', models.SmallIntegerField(blank=True, null=True)),
                ('fontweight', models.TextField(blank=True, null=True)),
                ('fontfamily', models.TextField(blank=True, null=True)),
                ('letterspace', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_value_desc_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreValueTitleTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('fontcolor', models.TextField(blank=True, null=True)),
                ('fontsize', models.SmallIntegerField(blank=True, null=True)),
                ('fontweight', models.TextField(blank=True, null=True)),
                ('fontfamily', models.TextField(blank=True, null=True)),
                ('letterspace', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_value_title_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FloatMenu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('iconcolor', models.TextField(blank=True, null=True)),
                ('fontfamily', models.TextField(blank=True, null=True)),
                ('bgcolor', models.TextField(blank=True, null=True)),
                ('fontcolor', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('svg', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'float_menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FloatMenuSubmenus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('file', models.TextField(blank=True, null=True)),
                ('fontfamily', models.TextField(blank=True, null=True)),
                ('bgcolor', models.TextField(blank=True, null=True)),
                ('fontcolor', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'float_menu_submenus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FloatMenuSubmenusTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'float_menu_submenus_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FloatMenuTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'float_menu_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FooterSocials',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('social', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('index', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'footer_socials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FooterUrls',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nameen', models.TextField(blank=True, db_column='nameEN', null=True)),
                ('namemn', models.TextField(blank=True, db_column='nameMN', null=True)),
                ('url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'footer_urls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManagementMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.TextField(blank=True, null=True)),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'management_member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.TextField(blank=True, null=True)),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shareholder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShareholderTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fullname', models.TextField(blank=True, null=True)),
                ('role', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shareholder_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.TextField(blank=True, null=True)),
                ('order', models.BigIntegerField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('visible', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'timeline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimelineTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('title_color', models.TextField(blank=True, null=True)),
                ('shortdesc', models.TextField(blank=True, null=True)),
                ('shortdesc_color', models.TextField(blank=True, null=True)),
                ('fulldesc', models.TextField(blank=True, null=True)),
                ('fulldesc_color', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'timeline_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VisionBlock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.TextField(blank=True, null=True)),
                ('file_ratio', models.TextField(blank=True, null=True)),
                ('visible', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vision_block',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VisionBlockDescTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True)),
                ('fontcolor', models.TextField(blank=True, null=True)),
                ('fontsize', models.BigIntegerField(blank=True, null=True)),
                ('fontweight', models.TextField(blank=True, null=True)),
                ('fontfamily', models.TextField(blank=True, null=True)),
                ('letterspace', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vision_block_desc_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VisionBlockTitleTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('fontcolor', models.TextField(blank=True, null=True)),
                ('fontsize', models.BigIntegerField(blank=True, null=True)),
                ('fontweight', models.SmallIntegerField(blank=True, null=True)),
                ('fontfamily', models.TextField(blank=True, null=True)),
                ('letterspace', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vision_block_title_translations',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='FooterTranslations',
        ),
    ]
