# Generated by Django 6.0.1 on 2026-02-12 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aboutpage_aboutpageblock_aboutpagemedia_and_more'),
    ]

    operations = [
        # Create Language table first (most dependencies)
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={'db_table': 'language', 'managed': True},
        ),
        # Create Category table
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={'db_table': 'category', 'managed': True},
        ),
        # Create ProductType table
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(blank=True, db_column='category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.category')),
            ],
            options={'db_table': 'product_type', 'managed': True},
        ),
        # Create Product table
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_type', models.ForeignKey(blank=True, db_column='product_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.producttype')),
            ],
            options={'db_table': 'product', 'managed': True},
        ),
        # Create Document table (for products/services)
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={'db_table': 'document', 'managed': True},
        ),
        # Create Collateral table (for products/services)
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={'db_table': 'collateral', 'managed': True},
        ),
        # Create Conditions table (for products/services)
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={'db_table': 'conditions', 'managed': True},
        ),
        # Create Services table
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={'db_table': 'services', 'managed': True},
        ),
    ]
