# Generated by Django 6.0.1 on 2026-02-12 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_create_initial_tables'),
    ]

    operations = [
        # All CreateModel operations removed — they were duplicates of 0003_create_initial_tables.
        # Collateral, Conditions, Document, and Services tables are already created in 0003.
    ]
