# Generated by Django 6.0.1 on 2026-02-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_create_services_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBanner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'about_banner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AboutBannerTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, default='')),
                ('subtitle', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'about_banner_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AboutPageBlockTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('fontcolor', models.TextField(blank=True, null=True)),
                ('fontsize', models.TextField(blank=True, null=True)),
                ('fontweight', models.TextField(blank=True, null=True)),
                ('fontfamily', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'about_page_block_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BranchCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'branch_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BranchPageSettings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('popup_bg', models.TextField(default='#ffffff')),
                ('popup_title_color', models.TextField(default='#111827')),
                ('popup_text_color', models.TextField(default='#374151')),
                ('popup_icon_color', models.TextField(default='#0d9488')),
                ('popup_btn_bg', models.TextField(default='#0d9488')),
                ('popup_btn_text', models.TextField(default='#ffffff')),
                ('popup_btn_label', models.TextField(default='Чиглэл авах')),
                ('card_bg', models.TextField(default='#ffffff')),
                ('card_border', models.TextField(default='#e5e7eb')),
                ('card_title_color', models.TextField(default='#111827')),
                ('card_text_color', models.TextField(default='#4b5563')),
                ('card_icon_color', models.TextField(default='#0d9488')),
                ('card_btn_bg', models.TextField(default='#f0fdfa')),
                ('card_btn_text', models.TextField(default='#0d9488')),
                ('card_btn_label', models.TextField(default='Газрын зургаас харах')),
                ('marker_color', models.TextField(default='#0d9488')),
                ('marker_selected_color', models.TextField(default='#0f766e')),
                ('map_btn_bg', models.TextField(default='#0d9488')),
                ('map_btn_text', models.TextField(default='#ffffff')),
                ('map_btn_label', models.TextField(default='Газрын зураг')),
            ],
            options={
                'db_table': 'branch_page_settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManagementCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'management_category',
                'ordering': ['sort_order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManagementCategoryTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'management_category_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManagementMemberTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('role', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'management_member_translations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsPageSettings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latest_heading', models.TextField(default='Сүүлийн мэдээнүүд')),
                ('featured_heading', models.TextField(default='Онцлох мэдээ')),
            ],
            options={
                'db_table': 'news_page_settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrgStructure',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chart_data', models.JSONField(default=dict)),
                ('title', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'org_structure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(default='', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('year_color', models.CharField(default='#0d9488', max_length=20)),
                ('title_color', models.CharField(default='#111827', max_length=20)),
                ('short_color', models.CharField(default='#4b5563', max_length=20)),
                ('desc_color', models.CharField(default='#4b5563', max_length=20)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'timeline_event',
                'ordering': ['sort_order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimelineEventTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('short_desc', models.TextField(blank=True, null=True)),
                ('full_desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'timeline_event_translations',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='collateral',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='conditions',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='managementmember',
            options={'managed': False, 'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='servicestranslations',
            options={'managed': False},
        ),
    ]
