# Generated by Django 6.0.1 on 2026-02-21 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_create_all_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('config_json', models.TextField(default='{}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exchange_rate_config',
            },
        ),
        migrations.CreateModel(
            name='FloatMenuSocials',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('platform', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('hover_color', models.TextField(blank=True, default='#0d9488', null=True)),
                ('sort_order', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'float_menu_socials',
            },
        ),
        migrations.CreateModel(
            name='LoanCalculatorConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(default='default', max_length=50, unique=True)),
                ('default_amount', models.BigIntegerField(default=10000000)),
                ('default_rate', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('default_term', models.IntegerField(default=12)),
                ('max_amount', models.BigIntegerField(default=100000000)),
                ('max_term', models.IntegerField(default=60)),
                ('min_rate', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('max_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('calc_btn_color', models.CharField(default='#0d9488', max_length=20)),
                ('calc_btn_font_size', models.CharField(default='14px', max_length=10)),
                ('calc_btn_text', models.CharField(default='Тооцоолох', max_length=100)),
                ('request_btn_color', models.CharField(default='#2563eb', max_length=20)),
                ('request_btn_font_size', models.CharField(default='14px', max_length=10)),
                ('request_btn_text', models.CharField(default='Хүсэлт илгээх', max_length=100)),
                ('request_btn_url', models.CharField(blank=True, default='', max_length=500)),
                ('disclaimer_color', models.CharField(default='#92400e', max_length=20)),
                ('disclaimer_font_size', models.CharField(default='10px', max_length=10)),
                ('disclaimer_text', models.TextField(default='Энэхүү тооцоолуур нь зөвхөн мэдээллийн зорилготой бөгөөд бодит зээлийн нөхцөл өөр байж болно.')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'loan_calculator_config',
            },
        ),
        migrations.CreateModel(
            name='SiteAnalytics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=64)),
                ('visitor_id', models.CharField(max_length=64)),
                ('page_path', models.CharField(max_length=500)),
                ('page_title', models.CharField(blank=True, default='', max_length=500)),
                ('referrer', models.CharField(blank=True, default='', max_length=500)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('device_type', models.CharField(blank=True, default='desktop', max_length=20)),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'site_analytics',
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.AlterModelOptions(
            name='aboutbanner',
            options={},
        ),
        migrations.AlterModelOptions(
            name='aboutbannertranslations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='aboutpage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='aboutpageblock',
            options={},
        ),
        migrations.AlterModelOptions(
            name='aboutpageblocktranslations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='aboutpagemedia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='aboutpagesection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='aboutpagesectiontranslations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='aboutpagetranslations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='appdownload',
            options={},
        ),
        migrations.AlterModelOptions(
            name='appdownloadlist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='appdownloadlisttranslation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='appdownloadtitle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='appdownloadtitleposition',
            options={},
        ),
        migrations.AlterModelOptions(
            name='appdownloadtitletranslation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='branchcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='branches',
            options={},
        ),
        migrations.AlterModelOptions(
            name='branchpagesettings',
            options={},
        ),
        migrations.AlterModelOptions(
            name='branchphone',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categorytranslations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='collateral',
            options={},
        ),
        migrations.AlterModelOptions(
            name='collateraltranslation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='conditions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='conditiontranslations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='corevalue',
            options={},
        ),
        migrations.AlterModelOptions(
            name='corevaluedesctranslations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='corevaluetitletranslations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ctasubtitle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ctatitle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
        migrations.AlterModelOptions(
            name='documenttranslation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='floatmenu',
            options={},
        ),
        migrations.AlterModelOptions(
            name='floatmenusubmenus',
            options={},
        ),
        migrations.AlterModelOptions(
            name='floatmenusubmenustranslations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='floatmenutranslations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='font',
            options={},
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='footersocials',
            options={},
        ),
        migrations.AlterModelOptions(
            name='footerurls',
            options={},
        ),
        migrations.AlterModelOptions(
            name='header',
            options={},
        ),
        migrations.AlterModelOptions(
            name='headermenu',
            options={},
        ),
        migrations.AlterModelOptions(
            name='headermenutranslation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='headerstyle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='headersubmenu',
            options={},
        ),
        migrations.AlterModelOptions(
            name='headersubmenutranslation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='headertertiarymenu',
            options={},
        ),
        migrations.AlterModelOptions(
            name='headertertiarymenutranslation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='heroslider',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hrpolicy',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hrpolicytranslations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jobs',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jobtranslations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={},
        ),
        migrations.AlterModelOptions(
            name='managementcategory',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='managementcategorytranslations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='managementmember',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='managementmembertranslations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.AlterModelOptions(
            name='newscategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='newscategorytranslations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='newscontenttranslations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='newsimages',
            options={},
        ),
        migrations.AlterModelOptions(
            name='newspagesettings',
            options={},
        ),
        migrations.AlterModelOptions(
            name='newsshortdesctranslations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='newssocials',
            options={},
        ),
        migrations.AlterModelOptions(
            name='newstitletranslations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orgstructure',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pagedescriptiontranslations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pages',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pagetitletranslations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productcollaterial',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productcondition',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productdetails',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productdocument',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producttranslations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producttypetranslations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicecard',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicecardtranslations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicecollateral',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicecondition',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicedocument',
            options={},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicestranslations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shareholder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shareholdertranslations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='timeline',
            options={},
        ),
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='timelineeventtranslations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='timelinetranslations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='visionblock',
            options={},
        ),
        migrations.AlterModelOptions(
            name='visionblockdesctranslations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='visionblocktitletranslations',
            options={},
        ),
        migrations.AddField(
            model_name='floatmenusocials',
            name='float_menu',
            field=models.ForeignKey(blank=True, db_column='float_menu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.floatmenu'),
        ),
    ]
