# Generated by Django 6.0.1 on 2026-03-10 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'about_page',
            },
        ),
        migrations.CreateModel(
            name='AppDownload',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.TextField(blank=True, null=True)),
                ('index', models.SmallIntegerField(blank=True, null=True)),
                ('appstore', models.TextField(blank=True, null=True)),
                ('playstore', models.TextField(blank=True, null=True)),
                ('bgcolor', models.TextField(blank=True, null=True)),
                ('fontcolor', models.TextField(blank=True, null=True)),
                ('titlecolor', models.TextField(blank=True, null=True)),
                ('iconcolor', models.TextField(blank=True, null=True)),
                ('buttonbgcolor', models.TextField(blank=True, null=True)),
                ('buttonfontcolor', models.TextField(blank=True, null=True)),
                ('googlebuttonbgcolor', models.TextField(blank=True, null=True)),
                ('googlebuttonfontcolor', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('layout', models.TextField(blank=True, default='standard', null=True)),
                ('mobile_layout', models.TextField(blank=True, default='image-top', null=True)),
                ('features_layout', models.TextField(blank=True, default='vertical', null=True)),
                ('fontfamily', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_download',
            },
        ),
        migrations.CreateModel(
            name='BranchCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('name_en', models.TextField(blank=True, default='', null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'branch_category',
            },
        ),
        migrations.CreateModel(
            name='BranchPageSettings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('popup_bg', models.TextField(default='#ffffff')),
                ('popup_title_color', models.TextField(default='#111827')),
                ('popup_text_color', models.TextField(default='#374151')),
                ('popup_icon_color', models.TextField(default='#0d9488')),
                ('popup_btn_bg', models.TextField(default='#0d9488')),
                ('popup_btn_text', models.TextField(default='#ffffff')),
                ('popup_btn_label', models.TextField(default='Чиглэл авах')),
                ('popup_btn_label_en', models.TextField(blank=True, default='', null=True)),
                ('card_bg', models.TextField(default='#ffffff')),
                ('card_border', models.TextField(default='#e5e7eb')),
                ('card_title_color', models.TextField(default='#111827')),
                ('card_text_color', models.TextField(default='#4b5563')),
                ('card_icon_color', models.TextField(default='#0d9488')),
                ('card_btn_bg', models.TextField(default='#f0fdfa')),
                ('card_btn_text', models.TextField(default='#0d9488')),
                ('card_btn_label', models.TextField(default='Газрын зургаас харах')),
                ('card_btn_label_en', models.TextField(blank=True, default='', null=True)),
                ('marker_color', models.TextField(default='#0d9488')),
                ('marker_selected_color', models.TextField(default='#0f766e')),
                ('map_btn_bg', models.TextField(default='#0d9488')),
                ('map_btn_text', models.TextField(default='#ffffff')),
                ('map_btn_label', models.TextField(default='Газрын зураг')),
                ('map_btn_label_en', models.TextField(blank=True, default='', null=True)),
                ('fontfamily', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'branch_page_settings',
            },
        ),
        migrations.CreateModel(
            name='CallButton',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('svg', models.TextField(blank=True, null=True)),
                ('button_color', models.TextField(blank=True, default='#ef4444', null=True)),
                ('icon_color', models.TextField(blank=True, default='#ffffff', null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'call_button',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'collateral',
            },
        ),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'conditions',
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.TextField(blank=True, null=True)),
                ('file_ratio', models.TextField(blank=True, null=True)),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('visible', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_value',
            },
        ),
        migrations.CreateModel(
            name='Cta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.TextField(blank=True, null=True)),
                ('collapsed_file', models.TextField(blank=True, null=True)),
                ('mobile_expanded_file', models.TextField(blank=True, null=True)),
                ('index', models.SmallIntegerField(blank=True, null=True)),
                ('font', models.TextField(blank=True, null=True)),
                ('description_font', models.TextField(blank=True, null=True)),
                ('subtitle_font', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('number', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CTA',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('config_json', models.TextField(default='{}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exchange_rate_config',
            },
        ),
        migrations.CreateModel(
            name='FloatMenu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('iconcolor', models.TextField(blank=True, null=True)),
                ('fontfamily', models.TextField(blank=True, null=True)),
                ('bgcolor', models.TextField(blank=True, null=True)),
                ('fontcolor', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('svg', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'float_menu',
            },
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('font', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'font',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('logotext', models.TextField(blank=True, null=True)),
                ('logo', models.TextField(blank=True, null=True)),
                ('svg', models.TextField(blank=True, null=True)),
                ('descmn', models.TextField(blank=True, db_column='descMN', null=True)),
                ('descen', models.TextField(blank=True, db_column='descEN', null=True)),
                ('locationmn', models.TextField(blank=True, db_column='locationMN', null=True)),
                ('locationen', models.TextField(blank=True, db_column='locationEN', null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('bgcolor', models.TextField(blank=True, db_column='bgColor', null=True)),
                ('fontcolor', models.TextField(blank=True, null=True)),
                ('featurecolor', models.TextField(blank=True, null=True)),
                ('socialiconcolor', models.TextField(blank=True, db_column='socialIconColor', null=True)),
                ('titlesize', models.TextField(blank=True, db_column='titleSize', null=True)),
                ('fontsize', models.TextField(blank=True, null=True)),
                ('fontfamily', models.TextField(blank=True, null=True)),
                ('copyrighten', models.TextField(blank=True, db_column='copyrightEN', null=True)),
                ('copyrightmn', models.TextField(blank=True, db_column='copyrightMN', null=True)),
                ('logo_size', models.TextField(blank=True, default='56', null=True)),
            ],
            options={
                'db_table': 'footer',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('logo', models.TextField(blank=True, null=True)),
                ('active', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'header',
                'db_table_comment': 'Headeer',
            },
        ),
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(blank=True, null=True)),
                ('file', models.TextField(blank=True, null=True)),
                ('time', models.SmallIntegerField(blank=True, null=True)),
                ('index', models.SmallIntegerField(blank=True, null=True)),
                ('visible', models.BooleanField(blank=True, null=True)),
                ('tablet_file', models.TextField(blank=True, null=True)),
                ('tablet_type', models.TextField(blank=True, default='i', null=True)),
                ('mobile_file', models.TextField(blank=True, null=True)),
                ('mobile_type', models.TextField(blank=True, default='i', null=True)),
            ],
            options={
                'db_table': 'hero_slider',
            },
        ),
        migrations.CreateModel(
            name='HrPolicy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.TextField(blank=True, null=True)),
                ('visual_type', models.TextField(blank=True, null=True)),
                ('visual_preset', models.TextField(blank=True, null=True)),
                ('font_color', models.TextField(blank=True, null=True)),
                ('bg_color', models.TextField(blank=True, null=True)),
                ('fontsize', models.TextField(blank=True, null=True)),
                ('fontfamily', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hr_policy',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.SmallIntegerField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.SmallIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lang_code', models.TextField(blank=True, null=True)),
                ('lang_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='LoanCalculatorConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(default='default', max_length=50, unique=True)),
                ('default_amount', models.BigIntegerField(default=10000000)),
                ('default_rate', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('default_term', models.IntegerField(default=12)),
                ('max_amount', models.BigIntegerField(default=100000000)),
                ('max_term', models.IntegerField(default=60)),
                ('min_rate', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('max_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('calc_btn_color', models.CharField(default='#0d9488', max_length=20)),
                ('calc_btn_font_size', models.CharField(default='14px', max_length=10)),
                ('calc_btn_text', models.CharField(default='Тооцоолох', max_length=100)),
                ('request_btn_color', models.CharField(default='#2563eb', max_length=20)),
                ('request_btn_font_size', models.CharField(default='14px', max_length=10)),
                ('request_btn_text', models.CharField(default='Хүсэлт илгээх', max_length=100)),
                ('request_btn_url', models.CharField(blank=True, default='', max_length=500)),
                ('disclaimer_color', models.CharField(default='#92400e', max_length=20)),
                ('disclaimer_font_size', models.CharField(default='10px', max_length=10)),
                ('disclaimer_text', models.TextField(default='Энэхүү тооцоолуур нь зөвхөн мэдээллийн зорилготой бөгөөд бодит зээлийн нөхцөл өөр байж болно.')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'loan_calculator_config',
            },
        ),
        migrations.CreateModel(
            name='ManagementCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'management_category',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ManagementMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='management', max_length=20)),
                ('image', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'management_member',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'news_category',
            },
        ),
        migrations.CreateModel(
            name='NewsPageSettings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latest_heading', models.TextField(default='Сүүлийн мэдээнүүд')),
                ('featured_heading', models.TextField(default='Онцлох мэдээ')),
                ('latest_heading_en', models.TextField(blank=True, default='', null=True)),
                ('featured_heading_en', models.TextField(blank=True, default='', null=True)),
                ('section_label_color', models.TextField(blank=True, default='#0d9488', null=True)),
                ('section_label_size', models.TextField(blank=True, default='14px', null=True)),
                ('heading_color', models.TextField(blank=True, default='#111827', null=True)),
                ('heading_size', models.TextField(blank=True, default='48px', null=True)),
                ('divider_color', models.TextField(blank=True, default='#0d9488', null=True)),
                ('button_color', models.TextField(blank=True, default='#0d9488', null=True)),
                ('button_text_color', models.TextField(blank=True, default='#ffffff', null=True)),
                ('button_size', models.TextField(blank=True, default='16px', null=True)),
            ],
            options={
                'db_table': 'news_page_settings',
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('style', models.SmallIntegerField(blank=True, null=True)),
                ('content_blocks', models.TextField(blank=True, default='[]', null=True)),
            ],
            options={
                'db_table': 'pages',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('logo', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, default='')),
                ('index', models.SmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'partners',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Service_card',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.TextField(blank=True, null=True)),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shareholder',
            },
        ),
        migrations.CreateModel(
            name='SiteAnalytics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=64)),
                ('visitor_id', models.CharField(max_length=64)),
                ('page_path', models.CharField(max_length=500)),
                ('page_title', models.CharField(blank=True, default='', max_length=500)),
                ('referrer', models.CharField(blank=True, default='', max_length=500)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('device_type', models.CharField(blank=True, default='desktop', max_length=20)),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'site_analytics',
            },
        ),
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label_mn', models.CharField(blank=True, default='', max_length=255)),
                ('label_en', models.CharField(blank=True, default='', max_length=255)),
                ('value', models.CharField(blank=True, default='', max_length=100)),
                ('prefix', models.CharField(blank=True, default='', max_length=50)),
                ('suffix', models.CharField(blank=True, default='+', max_length=50)),
                ('suffix_color', models.CharField(blank=True, default='', max_length=20)),
                ('icon', models.TextField(blank=True, null=True)),
                ('index', models.SmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stat_items',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StatsConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title_mn', models.CharField(blank=True, default='Бидний тоон үзүүлэлтүүд', max_length=255)),
                ('title_en', models.CharField(blank=True, default='Our key metrics', max_length=255)),
                ('description_mn', models.TextField(blank=True, default='Глобус санхүүгийн байгууллагын бодит тоон үзүүлэлтүүд, манай үйл ажиллагааны хэмжүүр.')),
                ('description_en', models.TextField(blank=True, default='Real performance metrics from Globus Financial, measuring our operational impact.')),
                ('section_image', models.TextField(blank=True, null=True)),
                ('value_color', models.CharField(blank=True, default='#1e293b', max_length=20)),
                ('value_font_size', models.CharField(blank=True, default='2.6rem', max_length=10)),
                ('label_color', models.CharField(blank=True, default='#94a3b8', max_length=20)),
                ('label_font_size', models.CharField(blank=True, default='0.875rem', max_length=10)),
                ('suffix_color', models.CharField(blank=True, default='#0048BA', max_length=20)),
                ('title_color', models.CharField(blank=True, default='#ffffff', max_length=20)),
                ('title_font_size', models.CharField(blank=True, default='1.75rem', max_length=10)),
                ('description_color', models.CharField(blank=True, default='rgba(255,255,255,0.7)', max_length=50)),
                ('description_font_size', models.CharField(blank=True, default='0.875rem', max_length=10)),
                ('mobile_title_font_size', models.CharField(blank=True, default='1.25rem', max_length=10)),
                ('mobile_description_font_size', models.CharField(blank=True, default='0.75rem', max_length=10)),
                ('mobile_value_font_size', models.CharField(blank=True, default='1.75rem', max_length=10)),
                ('mobile_label_font_size', models.CharField(blank=True, default='0.75rem', max_length=10)),
                ('fontfamily', models.TextField(blank=True, null=True)),
                ('text_active', models.BooleanField(default=True)),
                ('image_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stats_config',
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.TextField(blank=True, null=True)),
                ('order', models.BigIntegerField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('visible', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'timeline',
            },
        ),
        migrations.CreateModel(
            name='VisionBlock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.TextField(blank=True, null=True)),
                ('file_ratio', models.TextField(blank=True, null=True)),
                ('visible', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vision_block',
            },
        ),
        migrations.CreateModel(
            name='AboutBanner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.TextField(blank=True, default='')),
                ('mobile_image', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(blank=True, db_column='page', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aboutpage')),
            ],
            options={
                'db_table': 'about_banner',
            },
        ),
        migrations.CreateModel(
            name='AboutPageMedia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.TextField(blank=True, null=True)),
                ('aspect_ratio', models.TextField(blank=True, null=True)),
                ('about', models.ForeignKey(blank=True, db_column='about', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.aboutpage')),
            ],
            options={
                'db_table': 'about_page_media',
            },
        ),
        migrations.CreateModel(
            name='AboutPageSection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('index', models.SmallIntegerField(blank=True, null=True)),
                ('visible', models.BooleanField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('image_position', models.TextField(blank=True, default='right', null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('page', models.ForeignKey(blank=True, db_column='page', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.aboutpage')),
            ],
            options={
                'db_table': 'about_page_section',
            },
        ),
        migrations.CreateModel(
            name='AboutPageBlock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('index', models.SmallIntegerField(blank=True, null=True)),
                ('visible', models.BooleanField(blank=True, null=True)),
                ('section', models.ForeignKey(blank=True, db_column='section', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.aboutpagesection')),
            ],
            options={
                'db_table': 'about_page_block',
            },
        ),
        migrations.CreateModel(
            name='AppDownloadList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('icon', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('index', models.SmallIntegerField(blank=True, null=True)),
                ('labelmn', models.TextField(blank=True, null=True)),
                ('labelen', models.TextField(blank=True, null=True)),
                ('icon_url', models.TextField(blank=True, null=True)),
                ('app_download', models.ForeignKey(blank=True, db_column='app_download', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='app.appdownload')),
            ],
            options={
                'db_table': 'app_download_list',
            },
        ),
        migrations.CreateModel(
            name='AppDownloadTitle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('index', models.SmallIntegerField(blank=True, null=True)),
                ('labelmn', models.TextField(blank=True, null=True)),
                ('labelen', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('fontsize', models.TextField(blank=True, null=True)),
                ('fontweight', models.TextField(blank=True, null=True)),
                ('top', models.IntegerField(blank=True, null=True)),
                ('left', models.IntegerField(blank=True, db_column='left', null=True)),
                ('rotate', models.IntegerField(blank=True, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('app_download', models.ForeignKey(blank=True, db_column='app_download', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='app.appdownload')),
            ],
            options={
                'db_table': 'app_download_title',
            },
        ),
        migrations.CreateModel(
            name='AppDownloadTitlePosition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('index', models.SmallIntegerField(blank=True, null=True)),
                ('app_download_title', models.ForeignKey(blank=True, db_column='app_download_title', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.appdownloadtitle')),
            ],
            options={
                'db_table': 'app_download_title_position',
            },
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('name_en', models.TextField(blank=True, default='', null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('location_en', models.TextField(blank=True, default='', null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('area', models.TextField(blank=True, null=True)),
                ('area_en', models.TextField(blank=True, default='', null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('city_en', models.TextField(blank=True, default='', null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('district_en', models.TextField(blank=True, default='', null=True)),
                ('open', models.TextField(blank=True, null=True)),
                ('open_en', models.TextField(blank=True, default='', null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
                ('longitude', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.branchcategory')),
            ],
            options={
                'db_table': 'branches',
            },
        ),
        migrations.CreateModel(
            name='BranchPhone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, db_column='branch', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.branches')),
            ],
            options={
                'db_table': 'branch_phone',
            },
        ),
        migrations.CreateModel(
            name='FloatMenuSocials',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('platform', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('hover_color', models.TextField(blank=True, default='#0d9488', null=True)),
                ('sort_order', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('float_menu', models.ForeignKey(blank=True, db_column='float_menu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.floatmenu')),
            ],
            options={
                'db_table': 'float_menu_socials',
            },
        ),
        migrations.CreateModel(
            name='FloatMenuSubmenus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('file', models.TextField(blank=True, null=True)),
                ('fontfamily', models.TextField(blank=True, null=True)),
                ('bgcolor', models.TextField(blank=True, null=True)),
                ('fontcolor', models.TextField(blank=True, null=True)),
                ('svg', models.TextField(blank=True, null=True)),
                ('float_menu', models.ForeignKey(blank=True, db_column='float_menu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.floatmenu')),
            ],
            options={
                'db_table': 'float_menu_submenus',
            },
        ),
        migrations.CreateModel(
            name='FooterSocials',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('social', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('index', models.SmallIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('footer', models.ForeignKey(blank=True, db_column='footer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.footer')),
            ],
            options={
                'db_table': 'footer_socials',
            },
        ),
        migrations.CreateModel(
            name='FooterUrls',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nameen', models.TextField(blank=True, db_column='nameEN', null=True)),
                ('namemn', models.TextField(blank=True, db_column='nameMN', null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('footer', models.ForeignKey(blank=True, db_column='footer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.footer')),
            ],
            options={
                'db_table': 'footer_urls',
            },
        ),
        migrations.CreateModel(
            name='HeaderMenu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('font', models.TextField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('index', models.SmallIntegerField(blank=True, null=True)),
                ('visible', models.SmallIntegerField(blank=True, null=True)),
                ('header', models.ForeignKey(blank=True, db_column='header', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='app.header')),
            ],
            options={
                'db_table': 'header_menu',
            },
        ),
        migrations.CreateModel(
            name='HeaderStyle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bgcolor', models.TextField(blank=True, db_column='bgColor', null=True)),
                ('fontcolor', models.TextField(blank=True, db_column='fontColor', null=True)),
                ('hovercolor', models.TextField(blank=True, db_column='hoverColor', null=True)),
                ('height', models.SmallIntegerField(blank=True, null=True)),
                ('sticky', models.SmallIntegerField(blank=True, null=True)),
                ('max_width', models.TextField(blank=True, default='1240px', null=True)),
                ('logo_size', models.SmallIntegerField(blank=True, default=44, null=True)),
                ('header', models.ForeignKey(blank=True, db_column='header', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.header')),
            ],
            options={
                'db_table': 'header_style',
            },
        ),
        migrations.CreateModel(
            name='HeaderSubmenu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('font', models.TextField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('index', models.SmallIntegerField(blank=True, null=True)),
                ('visible', models.SmallIntegerField(blank=True, null=True)),
                ('header_menu', models.ForeignKey(blank=True, db_column='header_menu', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='app.headermenu')),
            ],
            options={
                'db_table': 'header_submenu',
            },
        ),
        migrations.CreateModel(
            name='HeaderTertiaryMenu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('font', models.TextField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('index', models.SmallIntegerField(blank=True, null=True)),
                ('visible', models.SmallIntegerField(blank=True, null=True)),
                ('header_submenu', models.ForeignKey(blank=True, db_column='header_submenu', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tertiary_menus', to='app.headersubmenu')),
            ],
            options={
                'db_table': 'header_tertiary_menu',
            },
        ),
        migrations.CreateModel(
            name='JobTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('department', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(blank=True, db_column='job', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.jobs')),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
            ],
            options={
                'db_table': 'job_translations',
            },
        ),
        migrations.CreateModel(
            name='HrPolicyTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('policy', models.ForeignKey(blank=True, db_column='policy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.hrpolicy')),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
            ],
            options={
                'db_table': 'hr_policy_translations',
            },
        ),
        migrations.CreateModel(
            name='HeaderTertiaryMenuTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('tertiary_menu', models.ForeignKey(blank=True, db_column='tertiary_menu', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.headertertiarymenu')),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
            ],
            options={
                'db_table': 'header_tertiary_menu_translation',
            },
        ),
        migrations.CreateModel(
            name='HeaderSubmenuTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('submenu', models.ForeignKey(blank=True, db_column='submenu', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.headersubmenu')),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
            ],
            options={
                'db_table': 'header_submenu_translation',
            },
        ),
        migrations.CreateModel(
            name='HeaderMenuTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('menu', models.ForeignKey(blank=True, db_column='menu', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.headermenu')),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
            ],
            options={
                'db_table': 'header_menu_translation',
            },
        ),
        migrations.CreateModel(
            name='FloatMenuTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('float_menu', models.ForeignKey(blank=True, db_column='float_menu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.floatmenu')),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
            ],
            options={
                'db_table': 'float_menu_translations',
            },
        ),
        migrations.CreateModel(
            name='FloatMenuSubmenusTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('float_menu_submenu', models.ForeignKey(blank=True, db_column='float_menu_submenu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.floatmenusubmenus')),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
            ],
            options={
                'db_table': 'float_menu_submenus_translations',
            },
        ),
        migrations.CreateModel(
            name='DocumentTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(blank=True, db_column='document', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.document')),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
            ],
            options={
                'db_table': 'document_translation',
            },
        ),
        migrations.CreateModel(
            name='CtaTitle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('cta', models.ForeignKey(blank=True, db_column='cta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.cta')),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
            ],
            options={
                'db_table': 'CTA_title',
            },
        ),
        migrations.CreateModel(
            name='CtaSubtitle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('cta', models.ForeignKey(blank=True, db_column='cta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.cta')),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
            ],
            options={
                'db_table': 'CTA_subtitle',
            },
        ),
        migrations.CreateModel(
            name='CoreValueTitleTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('fontcolor', models.TextField(blank=True, null=True)),
                ('fontsize', models.SmallIntegerField(blank=True, null=True)),
                ('fontweight', models.TextField(blank=True, null=True)),
                ('fontfamily', models.TextField(blank=True, null=True)),
                ('letterspace', models.TextField(blank=True, null=True)),
                ('textalign', models.TextField(blank=True, default='left', null=True)),
                ('corevalue', models.ForeignKey(blank=True, db_column='core_value', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.corevalue')),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
            ],
            options={
                'db_table': 'core_value_title_translations',
            },
        ),
        migrations.CreateModel(
            name='CoreValueDescTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('fontcolor', models.TextField(blank=True, null=True)),
                ('fontsize', models.SmallIntegerField(blank=True, null=True)),
                ('fontweight', models.TextField(blank=True, null=True)),
                ('fontfamily', models.TextField(blank=True, null=True)),
                ('letterspace', models.TextField(blank=True, null=True)),
                ('textalign', models.TextField(blank=True, default='left', null=True)),
                ('corevalue', models.ForeignKey(blank=True, db_column='core_value', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.corevalue')),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
            ],
            options={
                'db_table': 'core_value_desc_translations',
            },
        ),
        migrations.CreateModel(
            name='ConditionTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('condition', models.ForeignKey(blank=True, db_column='condition', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.conditions')),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
            ],
            options={
                'db_table': 'condition_translations',
            },
        ),
        migrations.CreateModel(
            name='CollateralTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('collateral', models.ForeignKey(blank=True, db_column='collateral', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.collateral')),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
            ],
            options={
                'db_table': 'collateral_translation',
            },
        ),
        migrations.CreateModel(
            name='CategoryTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, db_column='category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.category')),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
            ],
            options={
                'db_table': 'category_translations',
            },
        ),
        migrations.CreateModel(
            name='AppDownloadTitleTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('app_download_title', models.ForeignKey(blank=True, db_column='app_download_title', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.appdownloadtitle')),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
            ],
            options={
                'db_table': 'app_download_title_translation',
            },
        ),
        migrations.CreateModel(
            name='AppDownloadListTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('app_download_list', models.ForeignKey(blank=True, db_column='app_download_list', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.appdownloadlist')),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
            ],
            options={
                'db_table': 'app_download_list_translation',
            },
        ),
        migrations.CreateModel(
            name='AboutPageTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('font', models.TextField(blank=True, null=True)),
                ('family', models.TextField(blank=True, null=True)),
                ('weight', models.TextField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
                ('page', models.ForeignKey(blank=True, db_column='page', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.aboutpage')),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
            ],
            options={
                'db_table': 'about_page_translations',
            },
        ),
        migrations.CreateModel(
            name='AboutPageSectionTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('fontsize', models.TextField(blank=True, null=True)),
                ('fontweight', models.TextField(blank=True, null=True)),
                ('fontfamily', models.TextField(blank=True, null=True)),
                ('section', models.ForeignKey(blank=True, db_column='section', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.aboutpagesection')),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
            ],
            options={
                'db_table': 'about_page_section_translations',
            },
        ),
        migrations.CreateModel(
            name='AboutPageBlockTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('fontcolor', models.TextField(blank=True, null=True)),
                ('fontsize', models.TextField(blank=True, null=True)),
                ('fontweight', models.TextField(blank=True, null=True)),
                ('fontfamily', models.TextField(blank=True, null=True)),
                ('block', models.ForeignKey(blank=True, db_column='block', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aboutpageblock')),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
            ],
            options={
                'db_table': 'about_page_block_translations',
            },
        ),
        migrations.CreateModel(
            name='ManagementMemberTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('role', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('styles', models.TextField(blank=True, default='{}', null=True)),
                ('language', models.ForeignKey(db_column='language', on_delete=django.db.models.deletion.CASCADE, to='app.language')),
                ('member', models.ForeignKey(db_column='member', on_delete=django.db.models.deletion.CASCADE, to='app.managementmember')),
            ],
            options={
                'db_table': 'management_member_translations',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.TextField(blank=True, null=True)),
                ('video', models.TextField(blank=True, null=True)),
                ('video_orientation', models.TextField(blank=True, default='horizontal', null=True)),
                ('facebook_url', models.TextField(blank=True, default='', null=True)),
                ('feature', models.BooleanField(blank=True, null=True)),
                ('render', models.BooleanField(blank=True, null=True)),
                ('show_on_home', models.BooleanField(blank=True, default=False, null=True)),
                ('readtime', models.SmallIntegerField(blank=True, null=True)),
                ('slug', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, db_column='category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.newscategory')),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='NewsCategoryTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, db_column='category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.newscategory')),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
            ],
            options={
                'db_table': 'news_category_translations',
            },
        ),
        migrations.CreateModel(
            name='NewsContentTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('font', models.TextField(blank=True, null=True)),
                ('family', models.TextField(blank=True, null=True)),
                ('weight', models.TextField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
                ('news', models.ForeignKey(blank=True, db_column='news', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.news')),
            ],
            options={
                'db_table': 'news_content_translations',
            },
        ),
        migrations.CreateModel(
            name='NewsImages',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.TextField(blank=True, null=True)),
                ('news', models.ForeignKey(blank=True, db_column='news', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.news')),
            ],
            options={
                'db_table': 'news_images',
            },
        ),
        migrations.CreateModel(
            name='NewsShortdescTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('font', models.TextField(blank=True, null=True)),
                ('family', models.TextField(blank=True, null=True)),
                ('weight', models.TextField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
                ('news', models.ForeignKey(blank=True, db_column='news', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.news')),
            ],
            options={
                'db_table': 'news_shortdesc_translations',
            },
        ),
        migrations.CreateModel(
            name='NewsSocials',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('social', models.TextField(blank=True, null=True)),
                ('icon', models.TextField(blank=True, null=True)),
                ('news', models.ForeignKey(blank=True, db_column='news', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.news')),
            ],
            options={
                'db_table': 'news_socials',
            },
        ),
        migrations.CreateModel(
            name='NewsTitleTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('font', models.TextField(blank=True, null=True)),
                ('family', models.TextField(blank=True, null=True)),
                ('weight', models.TextField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
                ('news', models.ForeignKey(blank=True, db_column='news', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.news')),
            ],
            options={
                'db_table': 'news_title_translations',
            },
        ),
        migrations.CreateModel(
            name='OrgStructure',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chart_data', models.JSONField(default=dict)),
                ('title', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(blank=True, db_column='page', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aboutpage')),
            ],
            options={
                'db_table': 'org_structure',
            },
        ),
        migrations.CreateModel(
            name='PageDescriptionTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('font', models.TextField(blank=True, null=True)),
                ('family', models.TextField(blank=True, null=True)),
                ('weight', models.TextField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
                ('page', models.ForeignKey(blank=True, db_column='page', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.pages')),
            ],
            options={
                'db_table': 'page_description_translations',
            },
        ),
        migrations.CreateModel(
            name='PageTitleTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('font', models.TextField(blank=True, null=True)),
                ('family', models.TextField(blank=True, null=True)),
                ('weight', models.TextField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
                ('page', models.ForeignKey(blank=True, db_column='page', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.pages')),
            ],
            options={
                'db_table': 'page_title_translations',
            },
        ),
        migrations.CreateModel(
            name='ProductCollaterial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('collateral', models.ForeignKey(blank=True, db_column='collateral', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.collateral')),
                ('product', models.ForeignKey(blank=True, db_column='product', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
            options={
                'db_table': 'product_collaterial',
            },
        ),
        migrations.CreateModel(
            name='ProductCondition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('condition', models.ForeignKey(blank=True, db_column='condition', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.conditions')),
                ('product', models.ForeignKey(blank=True, db_column='product', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
            options={
                'db_table': 'product_condition',
            },
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_fee_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_fee_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('term_months', models.SmallIntegerField(blank=True, null=True)),
                ('min_processing_hours', models.SmallIntegerField(blank=True, null=True)),
                ('max_processing_hoyrs', models.SmallIntegerField(blank=True, null=True)),
                ('processing_time_minutes', models.IntegerField(blank=True, default=0, null=True)),
                ('fee_type', models.CharField(blank=True, default='fee', max_length=20)),
                ('calc_btn_color', models.CharField(blank=True, default='#0d9488', max_length=20)),
                ('calc_btn_font_size', models.CharField(blank=True, default='14px', max_length=10)),
                ('calc_btn_text', models.CharField(blank=True, default='Тооцоолох', max_length=100)),
                ('request_btn_color', models.CharField(blank=True, default='#2563eb', max_length=20)),
                ('request_btn_font_size', models.CharField(blank=True, default='14px', max_length=10)),
                ('request_btn_text', models.CharField(blank=True, default='Хүсэлт илгээх', max_length=100)),
                ('request_btn_url', models.CharField(blank=True, default='', max_length=500)),
                ('disclaimer_color', models.CharField(blank=True, default='#92400e', max_length=20)),
                ('disclaimer_font_size', models.CharField(blank=True, default='10px', max_length=10)),
                ('disclaimer_text', models.TextField(blank=True, default='Энэхүү тооцоолуур нь зөвхөн мэдээллийн зорилготой бөгөөд бодит зээлийн нөхцөл өөр байж болно.')),
                ('banner_image', models.CharField(blank=True, default='', max_length=500)),
                ('banner_mobile_image', models.CharField(blank=True, default='', max_length=500)),
                ('description_mn', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('description_color', models.CharField(blank=True, default='#ffffff', max_length=20)),
                ('description_font_size', models.CharField(blank=True, default='16px', max_length=10)),
                ('description_align', models.CharField(blank=True, default='center', max_length=10)),
                ('description_font_family', models.CharField(blank=True, default='', max_length=100)),
                ('product', models.ForeignKey(blank=True, db_column='product', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
            options={
                'db_table': 'product_details',
            },
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document', models.ForeignKey(blank=True, db_column='document', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.document')),
                ('product', models.ForeignKey(blank=True, db_column='product', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
            options={
                'db_table': 'product_document',
            },
        ),
        migrations.CreateModel(
            name='ProductTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
                ('product', models.ForeignKey(blank=True, db_column='product', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
            options={
                'db_table': 'product_translations',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(blank=True, db_column='category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.category')),
            ],
            options={
                'db_table': 'product_type',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, db_column='product_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.producttype'),
        ),
        migrations.CreateModel(
            name='ProductTypeTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
                ('product_type', models.ForeignKey(blank=True, db_column='product_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.producttype')),
            ],
            options={
                'db_table': 'product_type_translations',
            },
        ),
        migrations.CreateModel(
            name='ServiceCardTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('short_desc', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
                ('service_card', models.ForeignKey(blank=True, db_column='service_card', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.servicecard')),
            ],
            options={
                'db_table': 'Service_card_translations',
            },
        ),
        migrations.CreateModel(
            name='ServiceDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document', models.ForeignKey(blank=True, db_column='document', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.document')),
                ('service', models.ForeignKey(blank=True, db_column='service', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.services')),
            ],
            options={
                'db_table': 'service_document',
            },
        ),
        migrations.CreateModel(
            name='ServiceCondition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('condition', models.ForeignKey(blank=True, db_column='condition', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.conditions')),
                ('service', models.ForeignKey(blank=True, db_column='service', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.services')),
            ],
            options={
                'db_table': 'service_condition',
            },
        ),
        migrations.CreateModel(
            name='ServiceCollateral',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('collateral', models.ForeignKey(blank=True, db_column='collateral', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.collateral')),
                ('service', models.ForeignKey(blank=True, db_column='service', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.services')),
            ],
            options={
                'db_table': 'service_collateral',
            },
        ),
        migrations.AddField(
            model_name='servicecard',
            name='service',
            field=models.ForeignKey(blank=True, db_column='service', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.services'),
        ),
        migrations.CreateModel(
            name='ServicesTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
                ('service', models.ForeignKey(blank=True, db_column='service', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.services')),
            ],
            options={
                'db_table': 'Services_translations',
            },
        ),
        migrations.CreateModel(
            name='ShareholderTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fullname', models.TextField(blank=True, null=True)),
                ('role', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
                ('shareholder', models.ForeignKey(blank=True, db_column='shareholder', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.shareholder')),
            ],
            options={
                'db_table': 'shareholder_translations',
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(default='', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('year_color', models.CharField(default='#0d9488', max_length=20)),
                ('title_color', models.CharField(default='#111827', max_length=20)),
                ('short_color', models.CharField(default='#4b5563', max_length=20)),
                ('desc_color', models.CharField(default='#4b5563', max_length=20)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('page', models.ForeignKey(blank=True, db_column='page', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aboutpage')),
            ],
            options={
                'db_table': 'timeline_event',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TimelineTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('title_color', models.TextField(blank=True, null=True)),
                ('shortdesc', models.TextField(blank=True, null=True)),
                ('shortdesc_color', models.TextField(blank=True, null=True)),
                ('fulldesc', models.TextField(blank=True, null=True)),
                ('fulldesc_color', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
                ('timeline', models.ForeignKey(blank=True, db_column='timeline', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.timeline')),
            ],
            options={
                'db_table': 'timeline_translations',
            },
        ),
        migrations.CreateModel(
            name='VisionBlockDescTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True)),
                ('fontcolor', models.TextField(blank=True, null=True)),
                ('fontsize', models.BigIntegerField(blank=True, null=True)),
                ('fontweight', models.TextField(blank=True, null=True)),
                ('fontfamily', models.TextField(blank=True, null=True)),
                ('letterspace', models.BigIntegerField(blank=True, null=True)),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
                ('vision_block', models.ForeignKey(blank=True, db_column='vision_block', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.visionblock')),
            ],
            options={
                'db_table': 'vision_block_desc_translations',
            },
        ),
        migrations.CreateModel(
            name='VisionBlockTitleTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('fontcolor', models.TextField(blank=True, null=True)),
                ('fontsize', models.BigIntegerField(blank=True, null=True)),
                ('fontweight', models.SmallIntegerField(blank=True, null=True)),
                ('fontfamily', models.TextField(blank=True, null=True)),
                ('letterspace', models.BigIntegerField(blank=True, null=True)),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.language')),
                ('vision_block', models.ForeignKey(blank=True, db_column='vision_block', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.visionblock')),
            ],
            options={
                'db_table': 'vision_block_title_translations',
            },
        ),
        migrations.CreateModel(
            name='AboutBannerTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, default='')),
                ('subtitle', models.TextField(blank=True, default='')),
                ('fontfamily', models.TextField(blank=True, default='')),
                ('banner', models.ForeignKey(db_column='banner', on_delete=django.db.models.deletion.CASCADE, to='app.aboutbanner')),
                ('language', models.ForeignKey(db_column='language', on_delete=django.db.models.deletion.CASCADE, to='app.language')),
            ],
            options={
                'db_table': 'about_banner_translations',
                'unique_together': {('banner', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ManagementCategoryTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('styles', models.TextField(blank=True, default='{}', null=True)),
                ('category', models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.CASCADE, to='app.managementcategory')),
                ('language', models.ForeignKey(db_column='language', on_delete=django.db.models.deletion.CASCADE, to='app.language')),
            ],
            options={
                'db_table': 'management_category_translations',
                'unique_together': {('category', 'language')},
            },
        ),
        migrations.CreateModel(
            name='TimelineEventTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('short_desc', models.TextField(blank=True, null=True)),
                ('full_desc', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(db_column='event', on_delete=django.db.models.deletion.CASCADE, to='app.timelineevent')),
                ('language', models.ForeignKey(db_column='language', on_delete=django.db.models.deletion.CASCADE, to='app.language')),
            ],
            options={
                'db_table': 'timeline_event_translations',
                'unique_together': {('event', 'language')},
            },
        ),
    ]
