# Generated by Django 6.0.1 on 2026-03-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floatmenu',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
