# Generated by Django 6.0.1 on 2026-04-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_add_loan_request_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrSection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title_fontfamily', models.TextField(blank=True, default='')),
                ('title_fontsize', models.TextField(blank=True, default='32')),
                ('title_color', models.TextField(blank=True, default='#0f172a')),
                ('title_weight', models.TextField(blank=True, default='700')),
                ('subtitle_fontfamily', models.TextField(blank=True, default='')),
                ('subtitle_fontsize', models.TextField(blank=True, default='14')),
                ('subtitle_color', models.TextField(blank=True, default='#64748b')),
                ('subtitle_weight', models.TextField(blank=True, default='500')),
                ('desc_fontfamily', models.TextField(blank=True, default='')),
                ('desc_fontsize', models.TextField(blank=True, default='15')),
                ('desc_color', models.TextField(blank=True, default='#475569')),
                ('btn_bg', models.TextField(blank=True, default='#1e293b')),
                ('btn_color', models.TextField(blank=True, default='#ffffff')),
                ('btn_radius', models.TextField(blank=True, default='12')),
                ('btn_fontfamily', models.TextField(blank=True, default='')),
                ('btn_fontsize', models.TextField(blank=True, default='14')),
                ('btn_fontweight', models.TextField(blank=True, default='600')),
                ('section_bg', models.TextField(blank=True, default='rgba(255,255,255,0.7)')),
                ('section_border_radius', models.TextField(blank=True, default='16')),
                ('section_border_color', models.TextField(blank=True, default='transparent')),
                ('section_border_width', models.TextField(blank=True, default='0')),
                ('accent_gradient', models.TextField(blank=True, default='from-blue-500 via-indigo-500 to-purple-500')),
                ('icon_image', models.TextField(blank=True, default='')),
                ('icon_url', models.TextField(blank=True, default='')),
                ('policy_title_fontfamily', models.TextField(blank=True, default='')),
                ('policy_title_fontsize', models.TextField(blank=True, default='18')),
                ('policy_title_color', models.TextField(blank=True, default='#334155')),
                ('policy_title_weight', models.TextField(blank=True, default='600')),
                ('policy_desc_fontsize', models.TextField(blank=True, default='14')),
                ('policy_desc_color', models.TextField(blank=True, default='#64748b')),
                ('policy_card_bg', models.TextField(blank=True, default='#ffffff')),
                ('policy_card_border_color', models.TextField(blank=True, default='#e2e8f0')),
                ('policy_card_border_radius', models.TextField(blank=True, default='12')),
                ('jobs_title_fontfamily', models.TextField(blank=True, default='')),
                ('jobs_title_fontsize', models.TextField(blank=True, default='18')),
                ('jobs_title_color', models.TextField(blank=True, default='#0f172a')),
                ('jobs_title_weight', models.TextField(blank=True, default='600')),
                ('jobs_desc_fontsize', models.TextField(blank=True, default='14')),
                ('jobs_desc_color', models.TextField(blank=True, default='#475569')),
                ('jobs_card_bg', models.TextField(blank=True, default='#ffffff')),
                ('jobs_card_border_color', models.TextField(blank=True, default='#e2e8f0')),
                ('jobs_card_border_radius', models.TextField(blank=True, default='12')),
                ('jobs_badge_bg', models.TextField(blank=True, default='#f0fdf4')),
                ('jobs_badge_color', models.TextField(blank=True, default='#15803d')),
                ('btn_icon_image', models.TextField(blank=True, default='')),
                ('btn_icon_url', models.TextField(blank=True, default='')),
                ('policy_tab_icon_image', models.TextField(blank=True, default='')),
                ('policy_tab_icon_url', models.TextField(blank=True, default='')),
                ('jobs_tab_icon_image', models.TextField(blank=True, default='')),
                ('jobs_tab_icon_url', models.TextField(blank=True, default='')),
                ('jobs_icon_image', models.TextField(blank=True, default='')),
                ('jobs_icon_url', models.TextField(blank=True, default='')),
                ('policy_tab_active_bg', models.TextField(blank=True, default='#1e293b')),
                ('policy_tab_active_color', models.TextField(blank=True, default='#ffffff')),
                ('jobs_tab_active_bg', models.TextField(blank=True, default='#1e293b')),
                ('jobs_tab_active_color', models.TextField(blank=True, default='#ffffff')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hr_section',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrSectionTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, default='')),
                ('subtitle', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('btn_text', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'hr_section_translations',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='appdownloadlist',
            options={'ordering': ['index', 'id']},
        ),
        migrations.AlterModelOptions(
            name='appdownloadtitle',
            options={'ordering': ['index', 'id']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='appdownload',
            name='appstore_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='appdownload',
            name='playstore_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hrpolicy',
            name='icon_image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hrpolicy',
            name='icon_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobs',
            name='icon_image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobs',
            name='icon_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='loancalculatorconfig',
            name='banner_image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='loancalculatorconfig',
            name='banner_mobile_image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='loancalculatorconfig',
            name='subtitle_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='loancalculatorconfig',
            name='subtitle_mn',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='loancalculatorconfig',
            name='text_styles',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='loancalculatorconfig',
            name='title_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='loancalculatorconfig',
            name='title_mn',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='loanrequestpage',
            name='form_subtitle_en',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='loanrequestpage',
            name='form_subtitle_mn',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='loanrequestpage',
            name='form_title_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='loanrequestpage',
            name='form_title_mn',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='loanrequestpage',
            name='success_description_en',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='loanrequestpage',
            name='success_description_mn',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='loanrequestpage',
            name='success_subtitle_en',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='loanrequestpage',
            name='success_subtitle_mn',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='loanrequestpage',
            name='success_title_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='loanrequestpage',
            name='success_title_mn',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='loanrequestpage',
            name='text_styles',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producttype',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
