# Generated by Django 6.0.1 on 2026-04-09 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_hrsection_hrsectiontranslations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.TextField(blank=True, default='')),
                ('image', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('content', models.JSONField(blank=True, default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'about_category',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutCategoryTranslations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.CASCADE, to='app.aboutcategory')),
                ('language', models.ForeignKey(db_column='language', on_delete=django.db.models.deletion.CASCADE, to='app.language')),
            ],
            options={
                'db_table': 'about_category_translations',
                'unique_together': {('category', 'language')},
            },
        ),
    ]
