# Generated by Django 6.0.1 on 2026-04-09 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_aboutcategory_aboutcategorytranslations'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterEmails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.TextField(blank=True, null=True)),
                ('index', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('footer', models.ForeignKey(blank=True, db_column='footer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.footer')),
            ],
            options={
                'db_table': 'footer_emails',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='FooterPhones',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone', models.TextField(blank=True, null=True)),
                ('index', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('footer', models.ForeignKey(blank=True, db_column='footer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.footer')),
            ],
            options={
                'db_table': 'footer_phones',
                'ordering': ['index'],
            },
        ),
    ]
