# Generated by Django 6.0.1 on 2026-04-09 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_footeremails_footerphones'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvApplication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('position', models.TextField(blank=True, default='')),
                ('experience', models.TextField(blank=True, default='')),
                ('message', models.TextField(blank=True, default='')),
                ('cv_file', models.TextField(blank=True, default='')),
                ('status', models.SmallIntegerField(choices=[(0, 'Шинэ'), (1, 'Хянагдаж байна'), (2, 'Зөвшөөрсөн'), (3, 'Татгалзсан')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, db_column='job', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.jobs')),
            ],
            options={
                'db_table': 'cv_application',
                'ordering': ['-created_at'],
            },
        ),
    ]
