# Generated by Django 6.0.1 on 2026-04-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_cvapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='corevalue',
            name='card_size',
            field=models.TextField(blank=True, choices=[('large', 'Том дөрвөлжин'), ('small', 'Жижиг дөрвөлжин'), ('vertical', 'Босоо дөрвөлжин')], default='small', null=True),
        ),
    ]
