# Generated by Django 6.0.1 on 2026-04-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_add_card_size_to_corevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementmember',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
