# Generated by Django 6.0.1 on 2026-04-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_add_pinned_to_management_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='cta',
            name='description_position',
            field=models.TextField(blank=True, default='top', null=True),
        ),
    ]
