# Generated by Django 6.0.1 on 2026-04-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_add_description_position_to_cta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cta',
            name='description_align',
            field=models.TextField(blank=True, default='left', null=True),
        ),
    ]
