# Generated by Django 6.0.1 on 2026-04-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_adconfig_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTutorial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title_mn', models.CharField(blank=True, default='', max_length=255)),
                ('title_en', models.CharField(blank=True, default='', max_length=255)),
                ('video_url', models.TextField(blank=True, default='')),
                ('thumbnail_url', models.TextField(blank=True, null=True)),
                ('index', models.SmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_tutorials',
                'ordering': ['index', 'id'],
            },
        ),
    ]
