# Generated by Django 6.0.1 on 2026-04-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_producttutorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTutorialConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title_mn', models.CharField(blank=True, default='Бүтээгдэхүүний заавар', max_length=255)),
                ('title_en', models.CharField(blank=True, default='Product Instructions', max_length=255)),
                ('title_color', models.CharField(blank=True, default='#0f172a', max_length=20)),
                ('title_font_size', models.CharField(blank=True, default='1.875rem', max_length=10)),
                ('title_align', models.CharField(blank=True, default='center', max_length=10)),
                ('bg_color', models.CharField(blank=True, default='#ffffff', max_length=20)),
            ],
            options={
                'db_table': 'product_tutorial_config',
            },
        ),
    ]
