# Generated by Django 6.0.1 on 2026-04-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_producttutorialconfig_title_font_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcategory',
            name='page_url',
            field=models.TextField(blank=True, default='', help_text='Link to page builder page URL'),
        ),
        migrations.AlterField(
            model_name='producttutorialconfig',
            name='title_font_size',
            field=models.CharField(blank=True, default='1.875rem', max_length=20),
        ),
    ]
